2016-06-01 09:33:45,881 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 106, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-01 09:33:45,900 - __main__ - ERROR - ***** start logging ******
2016-06-01 15:01:47,207 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 106, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-01 15:01:47,208 - __main__ - ERROR - ***** start logging ******
2016-06-01 15:36:40,299 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 106, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-01 15:36:40,301 - __main__ - ERROR - ***** start logging ******
2016-06-03 09:12:48,256 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 106, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 09:12:48,268 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:03:34,466 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 113, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:03:34,469 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:04:55,274 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 113, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:04:55,277 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:06:55,975 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 113, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:06:55,978 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:07:58,806 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 113, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:07:58,811 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:08:41,093 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 115, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:08:41,096 - __main__ - ERROR - ***** start logging ******
2016-06-03 13:21:29,801 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 115, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-03 13:21:29,806 - __main__ - ERROR - ***** start logging ******
2016-06-06 09:31:22,815 - __main__ - ERROR - serial port opening problem.
Traceback (most recent call last):
  File "C:/Users/steun/Dropbox/data/aptana/nordic/new_server.py", line 115, in <module>
    s = Serial(SERIAL_PORT, SERIAL_SPEED)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialutil.py", line 180, in __init__
    self.open()
  File "C:\virtualenvs\nordic\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2016-06-06 09:31:22,853 - __main__ - ERROR - ***** start logging ******
